language: sh
sudo: false

env:
  - SCRIPTS='generate-script generate-readme pomfload'

addons:
  apt:
    packages:
      - ghc
      - cabal-install
      - devscripts
      - jq

install:
  - cabal update
  - git clone https://github.com/koalaman/shellcheck.git
  - cd shellcheck
  - cabal install
  - cd ..
  - export PATH="$HOME/.cabal/bin:$PATH"
  - which shellcheck

script:
  - checkbashisms -xp ${SCRIPTS}
  - shellcheck --shell=sh ${SCRIPTS}
  - jq . sites.json
  - jq -r "$(cat sites_to_help_text.jq)" sites.json
  - diff <(./generate-script) pomfload
  - diff <(./generate-readme) README.rst
