language: sh
sudo: false

env:
  - SCRIPTS='generate-script generate-readme pomfload'

addons:
  apt:
    sources:
      - fpcomplete-precise
    packages:
      - stack
      - devscripts
      - jq

install:
  - git clone https://github.com/koalaman/shellcheck.git
  - cd shellcheck
  - stack update
  - stack setup
  - stack install
  - cd ..
  - export PATH="$HOME/.local/bin:$PATH"
  - which shellcheck
  - shellcheck --version

script:
  - checkbashisms -xp ${SCRIPTS}
  - shellcheck --shell=sh ${SCRIPTS}
  - jq . sites.json
  - jq -r "$(cat sites_to_help_text.jq)" sites.json
  - diff <(./generate-script) pomfload
  - diff <(./generate-readme) README.rst
