language: sh
sudo: false

env:
  - SCRIPTS='generate-script generate-readme pomfload'

cache:
  directories:
    - $HOME/.stack

addons:
  apt:
    packages:
      # For ``stack`` usage
      - g++
      - gcc
      - libc6-dev
      - libffi-dev
      - libgmp-dev
      - make
      - xz-utils
      - zlib1g-dev
      - gnupg

      # For our purposes
      - devscripts
      - jq

install:
  - mkdir -p "$HOME/.local/bin"
  - export PATH="$HOME/.local/bin:$PATH"

  - mkdir stack_tmp
  - wget https://www.stackage.org/stack/linux-x86_64 -O stack.tar.gz
  - tar xzf stack.tar.gz -C stack_tmp
  - cp stack_tmp/*/stack "$HOME/.local/bin/"
  - which stack
  - stack --version

  - stack update
  - stack setup
  - stack path
  - test "$(stack path --stack-root)" = "$HOME/.stack"

  - stack install ShellCheck
  - which shellcheck
  - shellcheck --version

script:
  - CHECKBASHISMS_MSG="Allowed to fail due to some bugs in checkbashisms"
  - checkbashisms -xp ${SCRIPTS} || echo "${CHECKBASHISMS_MSG}"
  - shellcheck --shell=sh ${SCRIPTS}
  - jq . sites.json
  - jq -r "$(cat sites_to_help_text.jq)" sites.json
  - diff <(./generate-script) pomfload
  - diff <(./generate-readme) README.rst
