#! /bin/sh


exit_no_default() {
    echo "Please, set the valid default site name in sites.json" >&2
    exit 1
}

SITES_TEXT="$(jq -r "$(cat sites_to_help_text.jq)" sites.json | sed 's/^/    /')"
echo "${SITES_TEXT}" | grep -q ' (default)' || exit_no_default


cat <<'EOF_'
========
pomfload
========

.. image:: https://travis-ci.org/hcpl/pomfload.svg
    :target: https://travis-ci.org/hcpl/pomfload

.. code-block::

    Usage: pomfload [-u|-f|-p] [-s SITE] FILE...

    Options:
      -s SITE           Specify the site name to upload (default: comfy.moe)
      -u                Output URL
      -f                Output filename only
      -p                Output the same way as the server responses

    Supported sites:
EOF_

echo "${SITES_TEXT}"

cat <<'EOF_'


Requirements
------------

* POSIX-compatible shell
* Packages wth essential Unix tools, such as |coreutils|_, |sed| or
  their alternatives.
* |curl|_
* |jq|_

.. |coreutils| replace:: ``coreutils``
.. _coreutils: https://gnu.org/s/coreutils
.. |sed| replace:: ``sed``
.. |curl| replace:: ``curl``
.. _curl: https://curl.haxx.se/
.. |jq| replace:: ``jq``
.. _jq: https://stedolan.github.io/jq/


Customization
-------------

If you want to have your set of available sites, you can add or remove
sites in ``sites.json``, then execute:

.. code-block::

    $ ./generate-script > pomfload

That's all! *(at least, it should be that easy)*


How to Contribute
-----------------

Notes for ``sites.json``:

* Give some reasonable aliases (often one alias is sufficient).
* And make sure it can actually download (of course :) ).

Patches, suggestions and comments are welcome!


Credits
-------

* `Shizmob <https://github.com/Shizmob>`_'s `original pomfload <https://gist.github.com/Shizmob/7984374>`_
EOF_
